name: Auto deploy to NCP

on: 
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 최신 버전을 다운로드 받습니다.
        uses: actions/checkout@v4.1.1

      - name: 환경 변수를 설정합니다.
        run: |
          echo "NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL" >> .env
          echo "NEXT_PUBLIC_KAKAO_JS_KEY=$"NEXT_PUBLIC_KAKAO_JS_KEY" >> .env
          echo "NEXT_PUBLIC_KAKAOCHANNEL_PROFULE_ID=$"NEXT_PUBLIC_KAKAOCHANNEL_PROFULE_ID" >> .env
          echo "HTTPS=$HTTPS" >> .env
        env:
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          NEXT_PUBLIC_KAKAO_JS_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_JS_KEY }}
          NEXT_PUBLIC_KAKAOCHANNEL_PROFULE_ID: ${{ secrets.NEXT_PUBLIC_KAKAOCHANNEL_PROFULE_ID }}
          HTTPS: ${{ secrets.HTTPS }}

      - name: 도커 이미지를 생성하고 도커 허브에 업로드합니다.
        run: |
          docker login -u $DOCKER_ID -p $DOCKER_TOKEN
          docker build -t $DOCKER_REPO:$TAG ./
          docker push $DOCKER_REPO:$TAG
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          TAG: ${{ github.sha }}
        
        
